Add entires for issues fixed by Silverstripe CMS 4.8.0 release
FriendsOfPHP/security-advisories pull request #571
Opened 2021-06-08 01:56 UTC by emteknetnz

We released Silverstripe CMS 4.8.0 and related patch releases this week. We disclosed a few security issues with those releases.

2021-06-08 12:21 UTC, naderman requested changes

2021-06-08 12:21 UTC, naderman commented on silverstripe/framework/CVE-2020-26138.yaml
> +        versions: ['>=4.0.0', '<4.8.0']
The linked CVE says affected versions are "silverstripe/framework: ^3.0.0, ^4.0.0" and 4.7.4 was also a fixed version, so I think you need to add additional branches here?

2021-06-08 12:21 UTC, naderman commented on silverstripe/framework/CVE-2021-25817.yaml
> +        versions: ['>=4.0.0', '<4.8.0']
Based on the link the fix is already in 4.7.4?

2021-06-08 13:46 UTC, naderman commented on silverstripe/framework/CVE-2020-26136.yaml
> +reference: composer://silverstripe/graphql
Please create a separate "silverstripe/graphql" directory for the graphql package, the silverstripe/framework directory is only meant for the silverstripe/framework package.

2021-06-08 21:17 UTC, naderman commented on silverstripe/framework/CVE-2020-26138.yaml
> +        versions: ['>=3.0.0']
You still need to add an end to this constraint, the branch name has no impact on this, so this would indicate that all future versions after 3.0.0 forever are insecure. the test suite errors as this also overlaps with the constraint below. So just add '<4.0.0' if you mean to mark all 3.x versions as insecure.

2021-06-08 21:32 UTC, emteknetnz commented on silverstripe/framework/CVE-2020-26138.yaml
> +        versions: ['>=3.0.0']
Good point thanks, I've added a top constraint of 3.99.99

2021-06-09 09:46 UTC, stof commented on silverstripe/framework/CVE-2020-26138.yaml
> +        versions: ['>=3.0.0', '<3.99.99']
this should be `<4.0.0` as there is no patched 3.99.99 version.

2021-06-09 20:58 UTC, naderman commented on silverstripe/framework/CVE-2021-25817.yaml
> +        versions: ['>=4.0.0', '<4.8.0']
```suggestion
        versions: ['>=4.0.0', '<4.7.4']
```

2021-06-09 20:58 UTC, naderman commented on silverstripe/framework/CVE-2020-26138.yaml
> +        versions: ['>=3.0.0', '<3.99.99']
```suggestion
        versions: ['>=3.0.0', '<4.0.0']
```

2021-06-09 23:05 UTC, emteknetnz commented on silverstripe/framework/CVE-2020-26138.yaml
> +        versions: ['>=3.0.0', '<3.99.99']
I've updated to <4.0.0

2021-06-15 00:10 UTC, emteknetnz commented on silverstripe/framework/CVE-2021-25817.yaml
> +        versions: ['>=4.0.0', '<4.8.0']
Apologies, yes you're correct.  I have updated this.

2021-06-15 08:59 UTC, stof approved these changes

2021-06-15 09:43 UTC, merged