Add brotkrueml/schema
FriendsOfPHP/security-advisories pull request #635
Opened 2022-06-14 18:03 UTC by brotkrueml

2022-06-14 19:11 UTC, naderman requested changes

2022-06-14 19:11 UTC, naderman commented on brotkrueml/schema/2022-06-14-1.yaml
> +cve: ~
according to the link above CVE id is `CVE-2022-33154` and this should also be used for the filename then.

2022-06-14 20:01 UTC, ohader commented on brotkrueml/schema/2022-06-14-1.yaml
> +cve: ~
@brotkrueml Can you rename the file `2022-06-14-1.yaml` to `CVE-2022-33154.yaml` please? Thx in advance!

2022-06-15 06:42 UTC, ohader approved these changes

2022-06-15 16:13 UTC, merged