Add CVE-2022-48614 for mediawiki/semantic-media-wiki
FriendsOfPHP/security-advisories pull request #703
Opened 2023-12-16 02:49 UTC by jorgsowa

Reference: https://nvd.nist.gov/vuln/detail/CVE-2022-48614

2023-12-18 08:24 UTC, xabbuh requested changes

2023-12-18 08:24 UTC, xabbuh commented on mediawiki/semantic-media-wiki/CVE-2022-48614.yaml
> +link: 'https://nvd.nist.gov/vuln/detail/CVE-2022-48614'
I would link to https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_4.0.2 here

2023-12-18 10:51 UTC, stof commented on mediawiki/semantic-media-wiki/CVE-2022-48614.yaml
> +link: 'https://nvd.nist.gov/vuln/detail/CVE-2022-48614'
I agree

2023-12-18 19:16 UTC, jorgsowa commented on mediawiki/semantic-media-wiki/CVE-2022-48614.yaml
> +link: 'https://nvd.nist.gov/vuln/detail/CVE-2022-48614'
There are already some links in the repository which are not working. I think more reliable are links to NVD.

Maybe the solution would be to allow for more links and/or references? What do you think?

2024-02-07 08:39 UTC, stof approved these changes

2024-02-07 08:39 UTC, merged