Adding CVE-2024-28859 for SwiftMailer gadget chain in Symfony 1.x
FriendsOfPHP/security-advisories pull request #715
Opened 2024-03-17 08:36 UTC by darkpills

There is a deserialization gadget chain in SwiftMailer that impacts Symfony 1.x.
Adding this in both SwiftMailer and Symfony directories

2024-03-17 09:27 UTC, xabbuh requested changes

2024-03-17 09:27 UTC, xabbuh commented on symfony/symfony/CVE-2024-28859.yaml
> +reference: composer://symfony/symfony
```suggestion
reference: composer://friendsofsymfony1/symfony1
```

(and the filename needs to changed accordingly)

2024-03-17 09:27 UTC, xabbuh commented on swiftmailer/swiftmailer/CVE-2024-28859.yaml
> +reference: composer://swiftmailer/swiftmailer
```suggestion
reference: composer://friendsofsymfony1/swiftmailer
```

(and the filename needs to be changed accordingly)

2024-03-17 21:27 UTC, darkpills commented on swiftmailer/swiftmailer/CVE-2024-28859.yaml
> +reference: composer://swiftmailer/swiftmailer
Hello, @xabbuh , thank for you checks. `reference` for the file `swiftmailer/swiftmailer/CVE-2024-28859.yaml` corresponds to `swiftmailer/swiftmailer` repository. But it is archived and there has been a fork. So I suggest maybe making 2 files for referencing both repositories?

2024-03-17 21:29 UTC, darkpills commented
`php validator.php` fails asking for upper bounds to the version number but there is no upper bound since the issue is not resolved and won't be on `swiftmailer/swiftmailer` repository at least. How do you solve this situation?

2024-03-19 19:18 UTC, thirsch commented
> `php validator.php` fails asking for upper bounds to the version number but there is no upper bound since the issue is not resolved and won't be on `swiftmailer/swiftmailer` repository at least. How do you solve this situation?

Hi @darkpills, maybe just adding the latest release as the upper bound? As it is unlikely that there will come a new release in the archived repository. But I'm not sure, if it's the way to go here.

2024-03-19 19:24 UTC, thirsch commented on symfony/symfony/CVE-2024-28859.yaml
> +reference: composer://symfony/symfony
@darkpills as symfony1 was never installable via composer, maybe it's correct to only have one file for symfony1 but keep the approach of two files for swiftmailer?

2024-03-19 20:38 UTC, darkpills commented
@thirsch  I added upper bounds and aligned file path with composer path. I also added another CVE. I think it should be ok now.

2024-03-20 17:08 UTC, thePanz commented
Thank you @darkpills for taking care of this :+1:

2024-03-20 17:13 UTC, stof commented
an unpatched vulnerability is supported. But you should have `null` as the `time` as there would be not timestamp for the release of the patch.

2024-03-20 17:20 UTC, stof commented on friendsofsymfony1/swiftmailer/CVE-2024-28859.yaml
> +        time:     null
this time should be the time of the backport done in https://github.com/FriendsOfSymfony1/swiftmailer/pull/18 (the time of the merge to be exact)

2024-03-20 21:15 UTC, darkpills commented on swiftmailer/swiftmailer/CVE-2024-28859.yaml
> +        versions: ['>=5.0.0', '<=5.4.12']
@stof  thank you, i made the required changes

2024-04-17 10:36 UTC, stof approved these changes

2024-04-17 10:37 UTC, merged